name: Test

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Check if test files exist
        run: |
          ../../app.test.js

      - name: Run tests
        run: npm run test

      - name: Check if coverage directory exists
        run: |
          if ! ls ./coverage &> /dev/null; then
            echo "No coverage report generated"
            exit 1
          fi
