name: Security Check
on:
  pull_request:
    branches: [main]
jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run security scan
        uses: Nc0/npm-audit-action@v1.1.1
        with:
          level: high
